---
name: "Update daily - Horoscope"
on: push
#on:   
  #schedule:
    #- cron: "* * * * *"

env:
  FILE_WEBSITE: website.html
  LIST_SIGNES: BELIER TAUREAU GEMEAUX CANCER LION VIERGE BALANCE SCORPION SAGITTAIRE CAPRICORNE VERSEAU POISSONS

jobs:

  build_jour:
    env:
      URL: https://www.mon-horoscope-du-jour.com/horoscopes/quotidien/belier.htm
      FILE: docs/jour.json
      FILE_TMP: docs/jour_tmp.json
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get Website
      run: curl $URL -o $FILE_WEBSITE
    - name: Create JSON
      run: |
        echo "{" > $FILE
        echo "  \"date\": \"$(date +%F)\"," >> $FILE
        echo "  \"1\": \"$(cat $FILE_WEBSITE |grep '<p class="content-intro">' |awk -F'<p class="content-intro">' '{ print $2 }' |awk -F'</p>' '{ print $1 }' |sed 's/"/\\"/g' |sed 's/\ *$//g')\"," >> $FILE
        echo "  \"2\": \"$(cat $FILE_WEBSITE |grep 'astro-section-glass')\"," >> $FILE
        sed -i '$ s/.$//' $FILE
        echo "}" >> $FILE
    - name: Commit JSON
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add $FILE
        git commit -m "Generated $FILE" || true
        git pull --rebase
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
